main:
  - name: About
    url: '#about'
    weight: 1
  - name: Posts
    url: /posts/
    weight: 2
  - name: CV
    url: /cv/
    weight: 3
  # - name: Publication
    # url: /publication/
    # weight: 4
